# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

    authors = Author.create([{id: 1, name:'Pushkin'}, {id: 2, name: 'Dostoevskiy'},{id: 3, name: 'Shakespeare'}, {id: 4, name: 'Homer'}, {id: 5, name: 'Orwell'}, {id: 6, name: 'Tolkien'}, {id: 7, name: 'Cervantes'}, {id: 8, name: 'Austen'}, {id: 9, name: 'Hemingway'}, {id: 10, name: 'Fitzgerald'}])
    books = Book.create([
        {id: 1,author_id: 1, name: "Book 1"}, {id: 2,author_id: 1, name: "Book 2"}, {id: 3,author_id: 1, name: "Book 3"}, {id: 4,author_id: 1, name: "Book 4"}, {id: 5,author_id: 1, name: "Book 5"}, {id: 6,author_id: 1, name: "Book 6"}, {id: 7,author_id: 1, name: "Book 7"}, {id: 8,author_id: 1, name: "Book 8"}, {id: 9,author_id: 1, name: "Book 9"}, {id: 10,author_id: 1, name: "Book 10"},
        {id: 1,author_id: 2, name: "Book 1"}, {id: 2,author_id: 2, name: "Book 2"}, {id: 3,author_id: 2, name: "Book 3"}, {id: 4,author_id: 2, name: "Book 4"}, {id: 5,author_id: 2, name: "Book 5"}, {id: 6,author_id: 2, name: "Book 6"}, {id: 7,author_id: 2, name: "Book 7"}, {id: 8,author_id: 2, name: "Book 8"}, {id: 9,author_id: 2, name: "Book 9"}, {id: 10,author_id: 2, name: "Book 10"},  
        {id: 1,author_id: 3, name: "Book 1"}, {id: 2,author_id: 3, name: "Book 2"}, {id: 3,author_id: 3, name: "Book 3"}, {id: 4,author_id: 3, name: "Book 4"}, {id: 5,author_id: 3, name: "Book 5"}, {id: 6,author_id: 3, name: "Book 6"}, {id: 7,author_id: 3, name: "Book 7"}, {id: 8,author_id: 3, name: "Book 8"}, {id: 9,author_id: 3, name: "Book 9"}, {id: 10,author_id: 3, name: "Book 10"},  
        {id: 1,author_id: 4, name: "Book 1"}, {id: 2,author_id: 4, name: "Book 2"}, {id: 3,author_id: 4, name: "Book 3"}, {id: 4,author_id: 4, name: "Book 4"}, {id: 5,author_id: 4, name: "Book 5"}, {id: 6,author_id: 4, name: "Book 6"}, {id: 7,author_id: 4, name: "Book 7"}, {id: 8,author_id: 4, name: "Book 8"}, {id: 9,author_id: 4, name: "Book 9"}, {id: 10,author_id: 4, name: "Book 10"},  
        {id: 1,author_id: 5, name: "Book 1"}, {id: 2,author_id: 5, name: "Book 2"}, {id: 3,author_id: 5, name: "Book 3"}, {id: 4,author_id: 5, name: "Book 4"}, {id: 5,author_id: 5, name: "Book 5"}, {id: 6,author_id: 5, name: "Book 6"}, {id: 7,author_id: 5, name: "Book 7"}, {id: 8,author_id: 5, name: "Book 8"}, {id: 9,author_id: 5, name: "Book 9"}, {id: 10,author_id: 5, name: "Book 10"},  
        {id: 1,author_id: 6, name: "Book 1"}, {id: 2,author_id: 6, name: "Book 2"}, {id: 3,author_id: 6, name: "Book 3"}, {id: 4,author_id: 6, name: "Book 4"}, {id: 5,author_id: 6, name: "Book 5"}, {id: 6,author_id: 6, name: "Book 6"}, {id: 7,author_id: 6, name: "Book 7"}, {id: 8,author_id: 6, name: "Book 8"}, {id: 9,author_id: 6, name: "Book 9"}, {id: 10,author_id: 6, name: "Book 10"},  
        {id: 1,author_id: 7, name: "Book 1"}, {id: 2,author_id: 7, name: "Book 2"}, {id: 3,author_id: 7, name: "Book 3"}, {id: 4,author_id: 7, name: "Book 4"}, {id: 5,author_id: 7, name: "Book 5"}, {id: 6,author_id: 7, name: "Book 6"}, {id: 7,author_id: 7, name: "Book 7"}, {id: 8,author_id: 7, name: "Book 8"}, {id: 9,author_id: 7, name: "Book 9"}, {id: 10,author_id: 7, name: "Book 10"},  
        {id: 1,author_id: 8, name: "Book 1"}, {id: 2,author_id: 8, name: "Book 2"}, {id: 3,author_id: 8, name: "Book 3"}, {id: 4,author_id: 8, name: "Book 4"}, {id: 5,author_id: 8, name: "Book 5"}, {id: 6,author_id: 8, name: "Book 6"}, {id: 7,author_id: 8, name: "Book 7"}, {id: 8,author_id: 8, name: "Book 8"}, {id: 9,author_id: 8, name: "Book 9"}, {id: 10,author_id: 8, name: "Book 10"},  
        {id: 1,author_id: 9, name: "Book 1"}, {id: 2,author_id: 9, name: "Book 2"}, {id: 3,author_id: 9, name: "Book 3"}, {id: 4,author_id: 9, name: "Book 4"}, {id: 5,author_id: 9, name: "Book 5"}, {id: 6,author_id: 9, name: "Book 6"}, {id: 7,author_id: 9, name: "Book 7"}, {id: 8,author_id: 9, name: "Book 8"}, {id: 9,author_id: 9, name: "Book 9"}, {id: 10,author_id: 9, name: "Book 10"},  
        {id: 1,author_id: 10, name: "Book 1"}, {id: 2,author_id: 10, name: "Book 2"}, {id: 3,author_id: 10, name: "Book 3"}, {id: 4,author_id: 10, name: "Book 4"}, {id: 5,author_id: 10, name: "Book 5"}, {id: 6,author_id: 10, name: "Book 6"}, {id: 7,author_id: 10, name: "Book 7"}, {id: 8,author_id: 10, name: "Book 8"}, {id: 9,author_id: 10, name: "Book 9"}, {id: 10,author_id: 10, name: "Book 10"}  
    ])